# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always


# Spring Configuration
spring:
  #to enable colors when you run your app outside intellij
  output:
    ansi:
      enabled: always

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/aftas_v1?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: false

  liquibase:
    enabled: false
  main:
    lazy-initialization: true

logging:
  file:
    name: aftas-api.log
  level:
    root: INFO

springdoc:
  api-docs:
    path: /api-docs

token:
  signing:
    key: Q2lyNXNOTENrV1dNRGI2NDlJc1p5bTBxM2p1M2RZeTc1amtmbW1HRnZHST0=
  validity:
    access:
      in:
        minutes: 10
    refresh:
      in:
        month: 1